sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t userjalil/sample-react -f Dockerfile.dev .

script:
  - docker run -e CI=true userjalil/sample-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'sample-react'
  env: 'Samplereact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-122592716481'
  bucket_path: 'sample-react'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: '$AWS_SECRET_KEY'