sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t userjalil/sample-react -f Dockerfile.dev .

script:
  - docker run -e CI=true userjalil/sample-react npm run test -- --coverage